apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: pet-shop-prod

images:
- name: pet-shop-to-customize
  newName: 013484737363.dkr.ecr.us-east-1.amazonaws.com/prod_petshop_project
  newTag: ${IMAGE_TAG}